title: I Curso de implementación del sistema de control, vigilancia y monitoreo de la biodiversidad en Áreas de Conservación Regional - ACR
description: Entrenamiento presencial dirigido a personal de las ACR en Perú
baseurl: "/TallerACR2025" # the subpath of your site, e.g. /blog
url: "https://conservacion-amazonica-acca.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/images/transparent-logos.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/images/favicon.ico"

# Aux links for the upper right navigation
aux_links:
  "Conservación Amazónica - ACCA":
    - "//www.acca.org.pe/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.

# Supports true (default) or false
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2025 Conservación Amazónica - ACCA. Distribuído por <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edita esta página en GitHub."
gh_edit_repository: "https://github.com/Conservacion-Amazonica-ACCA/TallerACR2025" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
