title: I Curso de implementación del sistema de control, vigilancia y monitoreo de la biodiversidad en Áreas de Conservación Regional - ACR
description: Entrenamiento presencial dirigido a personal de las ACR en Perú

url: https://conservacion-amazonica-acca.github.io

aux_links:
  "Conservación Amazónica - ACCA":
    - "//www.acca.org.pe/"